### ISSUE TITLE
Screen Lock

### ISSUE THREAD

**Issue by herpdederp** [Kennyc1012/GlassMusicPlayer#1]
Using XE12 New Model

Every time I start the app on Glass, it locks up the screen. It does play the music though.

**Comment by Kennyc1012** [comment]
Are you using the newest apk that I have posted? I ran into that problem but I believed i fixed it. Also, how many songs do you have on your glass and does it freeze when you try to enter in your lockscreen pin?

**Comment by herpdederp** [comment]
I used the one updated 4 days ago. I put about 20 songs on and it does not allow me to go to the screen, it froze besides playing music.

**Comment by Kennyc1012** [comment]
I can't seem to replicate your issue. Try uninstalling through ADB then reinstalling again. If that does not help, please be at detailed as possible about what you are doing or running when it freezes.

**Comment by herpdederp** [comment]
I get the message "Home not responding" 
I'll try reinstall
