### ISSUE TITLE
XE16 Support?

### ISSUE THREAD

**Issue by amarine88** [Kennyc1012/GlassMusicPlayer#4]
Doesn't seem to work on XE16. The option to play music doesn't appear on the "Ok Glass" menu.

**Comment by Kennyc1012** [comment]
I haven't got a chance to update the app to the new version yet, have between busy. I will look at it in the next couple of days.

**Comment by amarine88** [comment]
Thanks for the quick reply! I wasn't expecting an instant fix, just wanted to file the bug. This app looks great, thank you for sharing.

**Comment by Kennyc1012** [comment]
Updated master branch, issue closed.

**Comment by amarine88** [comment]
Confirmed working. SLIGHT issue: the apk is named "Gass" not "Glass" took me a couple failed installs to notice ;) keep up the good work!
